/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam1_brauliocalix;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        usu.add(new usuarios("admin", "admin"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin = new javax.swing.JDialog();
        bt_agregar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        crearcuenta = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cr_fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cr_user = new javax.swing.JTextField();
        cr_contra = new javax.swing.JTextField();
        cr_num = new javax.swing.JTextField();
        cr_corre = new javax.swing.JTextField();
        cr_nombre = new javax.swing.JTextField();
        cr_gene = new javax.swing.JComboBox<>();
        crUSU = new javax.swing.JButton();
        ad_nuevo = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nu_desc = new javax.swing.JTextArea();
        nu_punt = new javax.swing.JComboBox<>();
        nu_copi = new javax.swing.JTextField();
        nu_gener = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nu_valor = new javax.swing.JTextField();
        nu_edi = new javax.swing.JTextField();
        nu_auto = new javax.swing.JTextField();
        nu_publi = new javax.swing.JTextField();
        nu_libro = new javax.swing.JButton();
        nu_titu = new javax.swing.JTextField();
        ad_modi = new javax.swing.JDialog();
        cb_libros = new javax.swing.JComboBox<>();
        ad_elimi = new javax.swing.JDialog();
        cb_elim = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ta_usu = new javax.swing.JTextField();
        bt_ingre = new javax.swing.JButton();
        bt_noti = new javax.swing.JButton();
        ta_contra = new javax.swing.JPasswordField();

        bt_agregar.setText("agregar");
        bt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarMouseClicked(evt);
            }
        });

        bt_modificar.setText("modificar");
        bt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarMouseClicked(evt);
            }
        });

        bt_eliminar.setText("eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        jLabel3.setText("MENU DEL ADMIN");

        jButton3.setText("regresar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin.getContentPane());
        Admin.getContentPane().setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel3)
                    .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(bt_agregar)
                .addGap(18, 18, 18)
                .addComponent(bt_modificar)
                .addGap(18, 18, 18)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(26, 26, 26))
        );

        jLabel4.setText("CRER USUARIOS");

        jLabel5.setText("user");

        jLabel6.setText("contra");

        jLabel7.setText("fecha");

        cr_fecha.setDateFormatString("dd,MM,yy");

        jLabel8.setText("numero");

        jLabel9.setText("correo");

        jLabel10.setText("nombre completo");

        jLabel11.setText("genero de lectura");

        cr_gene.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantasia", "Romance", "Accion", "Historia" }));

        crUSU.setText("Registrarse");
        crUSU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crUSUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crearcuentaLayout = new javax.swing.GroupLayout(crearcuenta.getContentPane());
        crearcuenta.getContentPane().setLayout(crearcuentaLayout);
        crearcuentaLayout.setHorizontalGroup(
            crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearcuentaLayout.createSequentialGroup()
                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearcuentaLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel4))
                    .addGroup(crearcuentaLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearcuentaLayout.createSequentialGroup()
                                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cr_user)
                                    .addComponent(cr_contra)
                                    .addComponent(cr_num)
                                    .addComponent(cr_corre)
                                    .addComponent(cr_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                            .addGroup(crearcuentaLayout.createSequentialGroup()
                                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cr_nombre)
                                    .addComponent(cr_gene, 0, 146, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addComponent(crUSU, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        crearcuentaLayout.setVerticalGroup(
            crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearcuentaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cr_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cr_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cr_fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cr_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cr_corre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearcuentaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cr_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cr_gene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearcuentaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crUSU, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );

        jLabel12.setText("titulo");

        jLabel13.setText("puntaje");

        jLabel14.setText("Descripcion");

        jLabel15.setText("cantidad de copias");

        nu_desc.setColumns(20);
        nu_desc.setRows(5);
        jScrollPane1.setViewportView(nu_desc);

        nu_punt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        nu_gener.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantasia", "Romance", "Accion", "Historia" }));

        jLabel16.setText("genero");

        jLabel17.setText("valor");

        jLabel18.setText("edicion");

        jLabel19.setText("autor");

        jLabel20.setText("año de publicacion");

        nu_libro.setText("crear libro");
        nu_libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nu_libroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ad_nuevoLayout = new javax.swing.GroupLayout(ad_nuevo.getContentPane());
        ad_nuevo.getContentPane().setLayout(ad_nuevoLayout);
        ad_nuevoLayout.setHorizontalGroup(
            ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_nuevoLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ad_nuevoLayout.createSequentialGroup()
                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ad_nuevoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nu_copi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(nu_publi))
                            .addGroup(ad_nuevoLayout.createSequentialGroup()
                                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(26, 26, 26)
                                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ad_nuevoLayout.createSequentialGroup()
                                                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel18))
                                                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel16)
                                                            .addComponent(jLabel17))))
                                                .addGap(66, 66, 66))
                                            .addGroup(ad_nuevoLayout.createSequentialGroup()
                                                .addComponent(nu_punt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel19)
                                                .addGap(76, 76, 76))
                                            .addGroup(ad_nuevoLayout.createSequentialGroup()
                                                .addComponent(nu_titu, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nu_gener, 0, 95, Short.MAX_VALUE)
                                    .addComponent(nu_valor)
                                    .addComponent(nu_edi)
                                    .addComponent(nu_auto, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(66, 66, 66))))
            .addGroup(ad_nuevoLayout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(nu_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ad_nuevoLayout.setVerticalGroup(
            ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_nuevoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nu_titu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nu_gener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(32, 32, 32)
                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(nu_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nu_edi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nu_punt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(nu_copi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(nu_publi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ad_nuevoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(ad_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(nu_auto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addComponent(nu_libro)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        cb_libros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout ad_modiLayout = new javax.swing.GroupLayout(ad_modi.getContentPane());
        ad_modi.getContentPane().setLayout(ad_modiLayout);
        ad_modiLayout.setHorizontalGroup(
            ad_modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_modiLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(cb_libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        ad_modiLayout.setVerticalGroup(
            ad_modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_modiLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(cb_libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jButton1.setText("eliminar el libro selecionado");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ad_elimiLayout = new javax.swing.GroupLayout(ad_elimi.getContentPane());
        ad_elimi.getContentPane().setLayout(ad_elimiLayout);
        ad_elimiLayout.setHorizontalGroup(
            ad_elimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_elimiLayout.createSequentialGroup()
                .addGroup(ad_elimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ad_elimiLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1))
                    .addGroup(ad_elimiLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(cb_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        ad_elimiLayout.setVerticalGroup(
            ad_elimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_elimiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(cb_elim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButton1)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("usuario");

        jLabel2.setText("contra");

        bt_ingre.setText("Ingresar");
        bt_ingre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ingreMouseClicked(evt);
            }
        });

        bt_noti.setText("No tienes cuenta ?");
        bt_noti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_notiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ta_usu, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(bt_ingre)
                            .addComponent(ta_contra)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(bt_noti)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ta_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ta_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(bt_ingre)
                .addGap(18, 18, 18)
                .addComponent(bt_noti)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ingreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ingreMouseClicked
        // TODO add your handling code here:
        String usua = ta_usu.getText();
        String contra = ta_contra.getText();
        boolean valido = false;
        for (int i = 0; i < usu.size(); i++) {
            if (usu.get(i).getContra().equals(contra) && usu.get(i).getUser().equals(usua)) {
                valido = true;
            }
        }
        if (valido == true) {
            JOptionPane.showMessageDialog(this, "Bienvenido: " + usua);
            if (usua.equals("admin")) {
                Admin.setModal(true);
                Admin.pack();
                Admin.setVisible(true);

            }
        } else {
            JOptionPane.showMessageDialog(this, "el usuario o la contraseña esta incorrecta");
            ta_contra.setText("");
            ta_usu.setText("");
        }
        ta_contra.setText("");
        ta_usu.setText("");
    }//GEN-LAST:event_bt_ingreMouseClicked

    private void bt_notiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_notiMouseClicked
        crearcuenta.setModal(true);
        crearcuenta.pack();
        crearcuenta.setVisible(true);
    }//GEN-LAST:event_bt_notiMouseClicked

    private void nu_libroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nu_libroMouseClicked
        String titulo = nu_titu.getText();
        String descrp = nu_desc.getText();
        int punta = nu_punt.getSelectedIndex() + 1;
        int cop = Integer.parseInt(nu_copi.getText());
        String gene = (String) nu_gener.getSelectedItem();
        int valor = Integer.parseInt(nu_valor.getText());
        String edicio = nu_edi.getText();
        String autor = nu_auto.getText();
        String año = nu_publi.getText();
        try {
            libros x = new libros(titulo, descrp, punta, cop, gene, valor, edicio, autor, año);
            libs.add(x);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros.getModel();
            modelo.addElement(x);
            cb_elim.setModel(modelo);
            cb_libros.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ad_nuevo, "hubo un problema para crear el libro");
        }
        JOptionPane.showMessageDialog(ad_nuevo, "se agrego de forma exitosa");

        ad_nuevo.dispose();
    }//GEN-LAST:event_nu_libroMouseClicked

    private void bt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarMouseClicked
        ad_nuevo.setModal(true);
        ad_nuevo.pack();
        ad_nuevo.setVisible(true);
    }//GEN-LAST:event_bt_agregarMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Admin.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void crUSUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crUSUMouseClicked
        // TODO add your handling code here:
        String user = "";
        try {
            user = cr_user.getText();
            if (user.equals("admin")) {

            } else {
                JOptionPane.showMessageDialog(crearcuenta, "no se puede llamar asi");
            }
        } catch (Exception e) {
        }

        String cont = cr_contra.getText();
        Date fecha = cr_fecha.getDate();
        String num = cr_num.getText();
        String corre = cr_corre.getText();
        String nombre = cr_nombre.getText();
        ArrayList<usuarios> ami = new ArrayList<>();
        ArrayList<libros> libos = new ArrayList<>();
        usu.add(new usuarios(user, cont, corre, nombre, corre, nombre, user, ami, libos));
        cr_contra.setText("");
        cr_corre.setText("");
        crearcuenta.dispose();
    }//GEN-LAST:event_crUSUMouseClicked

    private void bt_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modificarMouseClicked

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        // TODO add your handling code here:
        ad_elimi.setModal(true);
        ad_elimi.pack();
        ad_elimi.setVisible(true);
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int num = cb_elim.getSelectedIndex();
        num = num - 4;

        libs.remove(num);
        ad_elimi.dispose();
        JOptionPane.showMessageDialog(ad_elimi, "se elimino de forma correcta");
        ad_elimi.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Admin;
    private javax.swing.JDialog ad_elimi;
    private javax.swing.JDialog ad_modi;
    private javax.swing.JDialog ad_nuevo;
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_ingre;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_noti;
    private javax.swing.JComboBox<String> cb_elim;
    private javax.swing.JComboBox<String> cb_libros;
    private javax.swing.JButton crUSU;
    private javax.swing.JTextField cr_contra;
    private javax.swing.JTextField cr_corre;
    private com.toedter.calendar.JDateChooser cr_fecha;
    private javax.swing.JComboBox<String> cr_gene;
    private javax.swing.JTextField cr_nombre;
    private javax.swing.JTextField cr_num;
    private javax.swing.JTextField cr_user;
    private javax.swing.JDialog crearcuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nu_auto;
    private javax.swing.JTextField nu_copi;
    private javax.swing.JTextArea nu_desc;
    private javax.swing.JTextField nu_edi;
    private javax.swing.JComboBox<String> nu_gener;
    private javax.swing.JButton nu_libro;
    private javax.swing.JTextField nu_publi;
    private javax.swing.JComboBox<String> nu_punt;
    private javax.swing.JTextField nu_titu;
    private javax.swing.JTextField nu_valor;
    private javax.swing.JPasswordField ta_contra;
    private javax.swing.JTextField ta_usu;
    // End of variables declaration//GEN-END:variables
    ArrayList<usuarios> usu = new ArrayList();
    ArrayList<libros> libs = new ArrayList();
}
